// Microrearch — ข้อมูลเชื้อก่อโรค
// รูปภาพจาก Wikimedia Commons (CC-licensed) สามารถเปลี่ยนเป็นไฟล์ใน images/ ได้

const MICROBES = [
  // ============ BACTERIA ============
  {
    id: 'staph-aureus',
    name: 'Staphylococcus aureus',
    thai: 'สแตฟิโลค็อกคัส ออเรียส',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Staphylococcus_aureus_VISA_2.jpg/640px-Staphylococcus_aureus_VISA_2.jpg',
    categories: ['shape:coccus', 'gram:positive', 'oxygen:facultative'],
    characteristics: 'ค็อกคัสแกรมบวก เรียงตัวเป็นกลุ่มคล้ายพวงองุ่น (cluster) ขนาด 0.5–1.5 µm Catalase positive, Coagulase positive สามารถเจริญได้ทั้งมีและไม่มีออกซิเจน (Facultative anaerobe)',
    pathogenesis: 'ก่อโรคติดเชื้อที่ผิวหนัง เช่น ฝี หนอง impetigo, cellulitis, scalded skin syndrome, food poisoning จาก enterotoxin, toxic shock syndrome (TSST-1), endocarditis และ sepsis สายพันธุ์ดื้อยา MRSA เป็นปัญหาสำคัญในโรงพยาบาล',
    vector: 'แพร่จากคนสู่คนผ่านการสัมผัสโดยตรง พบเป็นเชื้อประจำถิ่นในจมูก ผิวหนัง และมือของผู้ป่วยและบุคลากร',
    additional: 'การวินิจฉัย: เพาะเชื้อบน Mannitol Salt Agar (เปลี่ยนเป็นสีเหลือง) การรักษา: ใช้ Cloxacillin, Vancomycin (สำหรับ MRSA)'
  },
  {
    id: 'strep-pneumo',
    name: 'Streptococcus pneumoniae',
    thai: 'สเตรปโตค็อกคัส นิวโมเนีย',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Streptococcus_pneumoniae.jpg/640px-Streptococcus_pneumoniae.jpg',
    categories: ['shape:coccus', 'gram:positive', 'oxygen:facultative'],
    characteristics: 'ค็อกคัสแกรมบวก รูปร่างคล้ายเปลวเทียน (lancet-shaped) เรียงตัวเป็นคู่ (diplococci) มีแคปซูล alpha-hemolytic บน blood agar, Optochin sensitive',
    pathogenesis: 'ก่อโรคปอดบวม (community-acquired pneumonia), หูชั้นกลางอักเสบ (otitis media), ไซนัสอักเสบ, เยื่อหุ้มสมองอักเสบ (meningitis), bacteremia',
    vector: 'แพร่ผ่านละอองฝอยทางเดินหายใจ (respiratory droplets) พบเป็นเชื้อประจำถิ่นใน nasopharynx',
    additional: 'มีวัคซีน PCV13, PPSV23 รักษาด้วย Penicillin, Ceftriaxone'
  },
  {
    id: 'strep-pyogenes',
    name: 'Streptococcus pyogenes',
    thai: 'สเตรปโตค็อกคัสกลุ่มเอ',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Streptococcus_pyogenes.jpg/640px-Streptococcus_pyogenes.jpg',
    categories: ['shape:coccus', 'gram:positive', 'oxygen:facultative'],
    characteristics: 'ค็อกคัสแกรมบวก เรียงตัวเป็นสาย (chain) Group A Streptococcus (GAS) Beta-hemolytic, Bacitracin sensitive มี M protein เป็น virulence factor สำคัญ',
    pathogenesis: 'คออักเสบ (strep throat), scarlet fever, impetigo, erysipelas, necrotizing fasciitis, streptococcal toxic shock syndrome ภาวะแทรกซ้อน: ไข้รูมาติก (rheumatic fever), acute glomerulonephritis',
    vector: 'แพร่ผ่านละอองฝอย และการสัมผัสโดยตรงกับแผล',
    additional: 'รักษา: Penicillin V (เลือกแรก), Erythromycin ในผู้แพ้ Penicillin'
  },
  {
    id: 'neisseria-gono',
    name: 'Neisseria gonorrhoeae',
    thai: 'เชื้อหนองใน',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Neisseria_gonorrhoeae_PHIL_3693_lores.jpg/640px-Neisseria_gonorrhoeae_PHIL_3693_lores.jpg',
    categories: ['shape:coccus', 'gram:negative', 'oxygen:aerobic'],
    characteristics: 'ค็อกคัสแกรมลบ เรียงตัวเป็นคู่คล้ายเมล็ดถั่ว (diplococci, kidney-shaped) Oxidase positive ต้องใช้ Thayer-Martin agar เพาะ',
    pathogenesis: 'หนองในแท้ (gonorrhea), urethritis, cervicitis, PID, septic arthritis, ophthalmia neonatorum (ตาเด็กแรกเกิดอักเสบ), disseminated gonococcal infection',
    vector: 'แพร่ผ่าน sexual contact, จากแม่สู่ลูกขณะคลอด',
    additional: 'รักษา: Ceftriaxone IM + Azithromycin (รักษา co-infection กับ Chlamydia)'
  },
  {
    id: 'ecoli',
    name: 'Escherichia coli',
    thai: 'อี.โคไล',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/EscherichiaColi_NIAID.jpg/640px-EscherichiaColi_NIAID.jpg',
    categories: ['shape:bacillus', 'gram:negative', 'oxygen:facultative'],
    characteristics: 'แท่งสั้นแกรมลบ (gram-negative rod) ขนาด 1–3 µm Lactose fermenter, Indole positive เจริญบน MacConkey agar เป็นโคโลนีสีชมพู',
    pathogenesis: 'UTI, ท้องเสีย (ETEC, EHEC O157:H7 ทำให้ HUS), neonatal meningitis, sepsis, traveler\'s diarrhea',
    vector: 'แพร่ทางอาหารและน้ำที่ปนเปื้อนอุจจาระ (fecal-oral route) พบเป็น normal flora ในลำไส้',
    additional: 'รักษาตาม sensitivity test มักใช้ Fluoroquinolones, Cephalosporins ระวังเชื้อดื้อยา ESBL'
  },
  {
    id: 'salmonella-typhi',
    name: 'Salmonella Typhi',
    thai: 'เชื้อไข้รากสาดน้อย',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/SalmonellaNIAID.jpg/640px-SalmonellaNIAID.jpg',
    categories: ['shape:bacillus', 'gram:negative', 'oxygen:facultative'],
    characteristics: 'แท่งแกรมลบ มี flagella รอบตัว (peritrichous) Non-lactose fermenter, H2S producer มี Vi antigen เป็น capsule',
    pathogenesis: 'ไข้ไทฟอยด์ (typhoid fever) ไข้สูงต่อเนื่อง, rose spots, hepatosplenomegaly, ภาวะแทรกซ้อน: ลำไส้ทะลุ (intestinal perforation), GI bleeding',
    vector: 'แพร่ทาง fecal-oral อาหารและน้ำที่ปนเปื้อน คนเป็น reservoir เพียงอย่างเดียว (chronic carrier)',
    additional: 'วินิจฉัย: Hemoculture (สัปดาห์แรก), Stool/Urine culture, Widal test รักษา: Ceftriaxone, Azithromycin'
  },
  {
    id: 'vibrio-cholerae',
    name: 'Vibrio cholerae',
    thai: 'เชื้ออหิวาตกโรค',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Cholera_bacteria_SEM.jpg/640px-Cholera_bacteria_SEM.jpg',
    categories: ['shape:bacillus', 'gram:negative', 'oxygen:facultative'],
    characteristics: 'แท่งโค้งคล้ายเครื่องหมายจุลภาค (comma-shaped) แกรมลบ มี polar flagellum เคลื่อนที่ฉับไว Oxidase positive เจริญใน TCBS agar',
    pathogenesis: 'อหิวาตกโรค (Cholera) ถ่ายเป็นน้ำคล้ายน้ำซาวข้าว (rice-water stool) จาก cholera toxin (cAMP↑) ทำให้สูญเสียน้ำและเกลือแร่อย่างรวดเร็ว ช็อก',
    vector: 'แพร่ทางน้ำและอาหาร โดยเฉพาะอาหารทะเลที่ปนเปื้อน',
    additional: 'รักษา: ORS, IV fluids, Doxycycline หรือ Azithromycin มีวัคซีนแบบกิน'
  },
  {
    id: 'mycobacterium-tb',
    name: 'Mycobacterium tuberculosis',
    thai: 'เชื้อวัณโรค',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/TB_Culture.jpg/640px-TB_Culture.jpg',
    categories: ['shape:bacillus', 'oxygen:aerobic'],
    characteristics: 'แท่งเรียวยาว (rod-shaped) ผนังเซลล์มี mycolic acid สูง ย้อมติดสีแดงด้วย Acid-Fast Stain (Ziehl-Neelsen) เจริญช้า (doubling time 18–24 ชม.) Strict aerobe',
    pathogenesis: 'วัณโรคปอด (pulmonary TB), วัณโรคนอกปอด เช่น TB meningitis, miliary TB, Pott\'s disease ก่อ granuloma แบบ caseous necrosis',
    vector: 'แพร่ทางอากาศผ่านละอองฝอย (airborne droplet nuclei) จากผู้ป่วยที่ไอ จาม',
    additional: 'วินิจฉัย: AFB smear, GeneXpert, Tuberculin skin test รักษาด้วยสูตร HRZE 6 เดือน'
  },
  {
    id: 'clostridium-tetani',
    name: 'Clostridium tetani',
    thai: 'เชื้อบาดทะยัก',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Clostridium_tetani_01.png/640px-Clostridium_tetani_01.png',
    categories: ['shape:bacillus', 'gram:positive', 'oxygen:anaerobic'],
    characteristics: 'แท่งแกรมบวก สร้างสปอร์ที่ปลายเซลล์รูป drumstick Strict anaerobe พบในดินและอุจจาระสัตว์',
    pathogenesis: 'โรคบาดทะยัก (Tetanus) จาก tetanospasmin toxin ที่ขัดขวางการหลั่ง GABA/glycine ทำให้กล้ามเนื้อเกร็งกระตุก trismus (lockjaw), opisthotonos',
    vector: 'เข้าสู่ร่างกายผ่านบาดแผลที่ปนเปื้อนดินหรือสนิม โดยเฉพาะแผลลึกขาดออกซิเจน',
    additional: 'ป้องกันด้วยวัคซีน DTP/Td รักษา: TIG (tetanus immunoglobulin), Metronidazole, ดูแลแผล'
  },
  {
    id: 'clostridium-botulinum',
    name: 'Clostridium botulinum',
    thai: 'เชื้อโบทูลินั่ม',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Clostridium_botulinum_01.png/640px-Clostridium_botulinum_01.png',
    categories: ['shape:bacillus', 'gram:positive', 'oxygen:anaerobic'],
    characteristics: 'แท่งแกรมบวก สร้างสปอร์รูป tennis racket Strict anaerobe ผลิต botulinum toxin ที่ทรงพลังที่สุดในธรรมชาติ',
    pathogenesis: 'Botulism — toxin ขัดขวางการหลั่ง acetylcholine ที่ neuromuscular junction ทำให้อ่อนแรงแบบ descending paralysis, double vision, หายใจล้มเหลว Infant botulism จากการกินน้ำผึ้ง',
    vector: 'อาหารกระป๋องที่ปนเปื้อนสปอร์ (เช่น หน่อไม้ปี๊บ ที่ในไทยเคยระบาด), น้ำผึ้งในเด็กทารก',
    additional: 'รักษา: Botulinum antitoxin, ใส่เครื่องช่วยหายใจ ใช้ทางการแพทย์/ความงามเป็น Botox'
  },
  {
    id: 'helicobacter-pylori',
    name: 'Helicobacter pylori',
    thai: 'เชื้อในกระเพาะอาหาร',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/EMpylori.jpg/640px-EMpylori.jpg',
    categories: ['shape:spirillum', 'gram:negative', 'oxygen:aerobic'],
    characteristics: 'แท่งโค้งงอเป็นเกลียว (spiral/curved) แกรมลบ มี flagella ที่ปลาย Urease positive Microaerophilic',
    pathogenesis: 'แผลในกระเพาะอาหาร (peptic ulcer), gastritis เรื้อรัง, มะเร็งกระเพาะอาหาร (gastric adenocarcinoma), MALT lymphoma',
    vector: 'แพร่ทาง fecal-oral หรือ oral-oral อาหารและน้ำที่ปนเปื้อน',
    additional: 'วินิจฉัย: Urea breath test, stool antigen, biopsy รักษา triple therapy: PPI + Amoxicillin + Clarithromycin'
  },
  {
    id: 'treponema-pallidum',
    name: 'Treponema pallidum',
    thai: 'เชื้อซิฟิลิส',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Treponema_pallidum.jpg/640px-Treponema_pallidum.jpg',
    categories: ['shape:spirochete', 'gram:negative'],
    characteristics: 'สไปโรคีตเรียว ขดเป็นเกลียวแน่น มองเห็นด้วย dark-field microscopy เพาะเลี้ยงในห้องปฏิบัติการไม่ได้',
    pathogenesis: 'ซิฟิลิส (Syphilis) มี 3 ระยะ: primary (chancre), secondary (rash, condyloma lata), tertiary (gumma, neurosyphilis, cardiovascular) congenital syphilis',
    vector: 'แพร่ผ่านการมีเพศสัมพันธ์ (sexually transmitted) และจากแม่สู่ลูกผ่านรก',
    additional: 'วินิจฉัย: VDRL, RPR, FTA-ABS รักษา: Benzathine Penicillin G'
  },
  {
    id: 'leptospira',
    name: 'Leptospira interrogans',
    thai: 'เชื้อเลปโตสไปร่า',
    kingdom: 'bacteria',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Leptospira_scanning_electron_micrograph.jpg/640px-Leptospira_scanning_electron_micrograph.jpg',
    categories: ['shape:spirochete', 'gram:negative', 'oxygen:aerobic'],
    characteristics: 'สไปโรคีตเรียวยาว มี hook ที่ปลายทั้งสองข้าง เคลื่อนที่ด้วย axial filaments มองด้วย dark-field microscopy',
    pathogenesis: 'โรคฉี่หนู (Leptospirosis) ไข้สูง ปวดน่อง ตาแดง ตับอักเสบ ไตวาย Weil\'s disease (severe icteric form) พบบ่อยในหน้าฝน หลังน้ำท่วม',
    vector: 'ปัสสาวะของหนูและสัตว์เลี้ยงลูกด้วยนมอื่นๆ ปนเปื้อนน้ำและดินเข้าทางผิวหนังแตก/เยื่อบุ',
    additional: 'วินิจฉัย: MAT (microscopic agglutination test), PCR รักษา: Doxycycline (mild), Penicillin G (severe)'
  },

  // ============ VIRUS ============
  {
    id: 'hiv',
    name: 'Human Immunodeficiency Virus (HIV)',
    thai: 'ไวรัสเอชไอวี',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/HIV-budding-Color.jpg/640px-HIV-budding-Color.jpg',
    categories: ['genetic:rna', 'envelope:enveloped'],
    characteristics: 'Retrovirus (Lentivirus) ssRNA สองเส้น มี enzyme reverse transcriptase, integrase, protease มีเยื่อหุ้ม (envelope) ขนาดประมาณ 100 nm มี gp120/gp41',
    pathogenesis: 'เข้าทำลาย CD4+ T cells ผ่าน gp120 binding กับ CD4 + CCR5/CXCR4 ทำให้ภูมิคุ้มกันบกพร่อง (AIDS) ติดเชื้อฉวยโอกาส เช่น PCP, TB, Toxoplasma, Cryptococcus',
    vector: 'แพร่ผ่านเลือด, sexual contact, จากแม่สู่ลูก (vertical transmission), เข็มฉีดยาที่ใช้ร่วมกัน',
    additional: 'วินิจฉัย: Anti-HIV antibody, p24 antigen, viral load (PCR) รักษา: ART (combination antiretroviral therapy)'
  },
  {
    id: 'sars-cov-2',
    name: 'SARS-CoV-2',
    thai: 'ไวรัสโคโรนาสายพันธุ์ใหม่',
    kingdom: 'virus',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/SARS-CoV-2_without_background.png/640px-SARS-CoV-2_without_background.png',
    categories: ['genetic:rna', 'envelope:enveloped'],
    characteristics: 'Coronavirus, ssRNA สายเดี่ยว positive-sense ขนาดใหญ่ที่สุดในกลุ่ม RNA virus มีเยื่อหุ้มและ spike protein (S) เข้าเซลล์ผ่าน ACE2 receptor',
    pathogenesis: 'COVID-19 อาการตั้งแต่ไม่มีอาการจนถึง ARDS, multi-organ failure ก่อ cytokine storm, microthrombosis, long COVID',
    vector: 'แพร่ผ่านละอองฝอยทางเดินหายใจ (respiratory droplets) และ aerosol',
    additional: 'วินิจฉัย: RT-PCR, ATK รักษา: Favipiravir, Molnupiravir, Paxlovid, Remdesivir มีวัคซีน mRNA และ inactivated'
  },
  {
    id: 'influenza',
    name: 'Influenza A virus',
    thai: 'ไวรัสไข้หวัดใหญ่',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/EM_of_influenza_virus.jpg/640px-EM_of_influenza_virus.jpg',
    categories: ['genetic:rna', 'envelope:enveloped'],
    characteristics: 'Orthomyxovirus, ssRNA negative-sense แบบแยกส่วน 8 segments มี HA (hemagglutinin) และ NA (neuraminidase) เป็น surface glycoprotein เกิด antigenic drift/shift',
    pathogenesis: 'ไข้หวัดใหญ่ (influenza) ไข้สูง ปวดเมื่อย ปวดศีรษะ ไอ ในเด็กและผู้สูงอายุอาจรุนแรงเป็นปอดบวม สายพันธุ์ระบาดใหญ่: H1N1, H5N1, H7N9',
    vector: 'แพร่ผ่านละอองฝอยทางเดินหายใจ สัตว์ปีกและสุกรเป็น reservoir',
    additional: 'รักษา: Oseltamivir (Tamiflu), Zanamivir มีวัคซีนประจำปี'
  },
  {
    id: 'dengue',
    name: 'Dengue virus',
    thai: 'ไวรัสไข้เลือดออก',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Dengue.jpg/640px-Dengue.jpg',
    categories: ['genetic:rna', 'envelope:enveloped'],
    characteristics: 'Flavivirus, ssRNA positive-sense มีเยื่อหุ้ม มี 4 serotypes (DENV-1 ถึง 4) การติดเชื้อซ้ำต่างชนิดทำให้รุนแรงขึ้น (ADE)',
    pathogenesis: 'ไข้เลือดออกเดงกี (Dengue Fever, DHF, DSS) ไข้สูง ปวดเมื่อย ปวดกระบอกตา ผื่น ในระยะวิกฤต plasma leakage, hemoconcentration, ช็อก',
    vector: 'ยุงลาย Aedes aegypti, Aedes albopictus เป็นพาหะ กัดในช่วงกลางวัน',
    additional: 'วินิจฉัย: NS1 antigen, IgM/IgG, PCR รักษา: ประคับประคอง ห้ามใช้ NSAIDs/Aspirin มีวัคซีน Dengvaxia'
  },
  {
    id: 'hepatitis-b',
    name: 'Hepatitis B Virus',
    thai: 'ไวรัสตับอักเสบบี',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Hepatitis_B_virus_v2.png/640px-Hepatitis_B_virus_v2.png',
    categories: ['genetic:dna', 'envelope:enveloped'],
    characteristics: 'Hepadnavirus, partial dsDNA วงกลม มี HBsAg ที่ envelope, HBcAg ที่ core มี reverse transcriptase ใช้ในการ replicate ผ่าน RNA intermediate',
    pathogenesis: 'ตับอักเสบเฉียบพลัน/เรื้อรัง, cirrhosis, hepatocellular carcinoma (HCC) เกิดจากภูมิคุ้มกันทำลายเซลล์ตับที่ติดเชื้อ',
    vector: 'แพร่ทางเลือด, sexual contact, จากแม่สู่ลูก (perinatal), เข็มฉีดยา',
    additional: 'วินิจฉัย: HBsAg, anti-HBc, HBeAg, HBV DNA ป้องกัน: วัคซีน HBV รักษาเรื้อรัง: Tenofovir, Entecavir'
  },
  {
    id: 'hsv',
    name: 'Herpes Simplex Virus (HSV)',
    thai: 'ไวรัสเริม',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Herpes_simplex_virus_TEM_B82-0474_lores.jpg/640px-Herpes_simplex_virus_TEM_B82-0474_lores.jpg',
    categories: ['genetic:dna', 'envelope:enveloped'],
    characteristics: 'Herpesvirus, dsDNA สายตรง มีเยื่อหุ้ม สามารถซ่อนตัวใน sensory ganglia (latency) HSV-1 (oral), HSV-2 (genital)',
    pathogenesis: 'เริมที่ปาก/อวัยวะเพศ, herpetic whitlow, herpes encephalitis (อันตรายถึงชีวิต), neonatal herpes, keratitis',
    vector: 'แพร่ผ่านการสัมผัสโดยตรงกับแผลหรือสารคัดหลั่ง (น้ำลาย, secretion)',
    additional: 'วินิจฉัย: Tzanck smear, PCR รักษา: Acyclovir, Valacyclovir'
  },
  {
    id: 'norovirus',
    name: 'Norovirus',
    thai: 'โนโรไวรัส',
    kingdom: 'virus',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Norovirus.jpg/640px-Norovirus.jpg',
    categories: ['genetic:rna', 'envelope:naked'],
    characteristics: 'Calicivirus, ssRNA positive-sense ไม่มีเยื่อหุ้ม (non-enveloped) ขนาดเล็ก 27–35 nm capsid icosahedral',
    pathogenesis: 'ท้องเสียเฉียบพลัน อาเจียน คลื่นไส้ เป็นสาเหตุหลักของ gastroenteritis ในผู้ใหญ่ พบระบาดในเรือสำราญ โรงเรียน',
    vector: 'แพร่ทาง fecal-oral, อาหารและน้ำปนเปื้อน, การสัมผัสพื้นผิว ติดต่อง่ายมาก (infectious dose ต่ำมาก ~18 viral particles)',
    additional: 'รักษาประคับประคอง ให้สารน้ำทดแทน ไม่มียาต้านไวรัสจำเพาะ'
  },
  {
    id: 'rotavirus',
    name: 'Rotavirus',
    thai: 'ไวรัสโรต้า',
    kingdom: 'virus',
    icon: '🦠',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Rotavirus_Reconstruction.jpg/640px-Rotavirus_Reconstruction.jpg',
    categories: ['genetic:rna', 'envelope:naked'],
    characteristics: 'Reovirus, dsRNA แบบแยกส่วน 11 segments ไม่มีเยื่อหุ้ม รูปร่างคล้ายล้อรถ (wheel-like)',
    pathogenesis: 'ท้องเสียเฉียบพลันในเด็กเล็ก (น้อยกว่า 5 ปี) อาเจียน ไข้ ขาดน้ำรุนแรง สาเหตุหลักของการเสียชีวิตจากท้องเสียทั่วโลก',
    vector: 'แพร่ทาง fecal-oral ทนต่อสภาพแวดล้อม',
    additional: 'ป้องกัน: วัคซีน Rotavirus (Rotarix, RotaTeq) รักษา: ORS, IV fluids'
  },
  {
    id: 'hpv',
    name: 'Human Papillomavirus (HPV)',
    thai: 'ไวรัสเอชพีวี',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Papilloma_Virus_%28HPV%29_EM.jpg/640px-Papilloma_Virus_%28HPV%29_EM.jpg',
    categories: ['genetic:dna', 'envelope:naked'],
    characteristics: 'Papillomavirus, dsDNA วงกลม ไม่มีเยื่อหุ้ม capsid icosahedral มีกว่า 200 สายพันธุ์ High-risk types: 16, 18',
    pathogenesis: 'หูดที่ผิวหนัง (common warts), หูดอวัยวะเพศ (condyloma acuminata), มะเร็งปากมดลูก (cervical cancer), oropharyngeal cancer',
    vector: 'แพร่ผ่าน sexual contact, skin-to-skin contact',
    additional: 'ป้องกัน: วัคซีน HPV (Gardasil 9) คัดกรอง: Pap smear, HPV DNA test'
  },
  {
    id: 'rabies',
    name: 'Rabies virus',
    thai: 'ไวรัสพิษสุนัขบ้า',
    kingdom: 'virus',
    icon: '🧬',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Rabies_Virus_EM_PHIL_1876.JPG/640px-Rabies_Virus_EM_PHIL_1876.JPG',
    categories: ['genetic:rna', 'envelope:enveloped'],
    characteristics: 'Rhabdovirus, ssRNA negative-sense รูปร่างคล้ายกระสุนปืน (bullet-shaped) มีเยื่อหุ้ม',
    pathogenesis: 'โรคพิษสุนัขบ้า (Rabies) — encephalitis เฉียบพลัน กลัวน้ำ (hydrophobia), กลืนลำบาก, agitation พบ Negri bodies ในเซลล์ประสาท เสียชีวิต ~100% เมื่อมีอาการ',
    vector: 'การกัดหรือข่วนของสัตว์เลี้ยงลูกด้วยนมที่ติดเชื้อ (สุนัข แมว ค้างคาว) ผ่านน้ำลาย',
    additional: 'ป้องกัน: ล้างแผล + Rabies immunoglobulin + วัคซีน (post-exposure prophylaxis ทันที)'
  },

  // ============ PARASITES ============
  {
    id: 'plasmodium',
    name: 'Plasmodium falciparum',
    thai: 'เชื้อมาลาเรีย',
    kingdom: 'parasite',
    icon: '🪲',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Plasmodium_falciparum_01.png/640px-Plasmodium_falciparum_01.png',
    categories: ['type:protozoa'],
    characteristics: 'Protozoa, Apicomplexan, intracellular parasite ใน RBC ระยะ ring form, trophozoite, schizont, gametocyte (รูป banana-shaped) ในคน',
    pathogenesis: 'ไข้มาลาเรียชนิดรุนแรง (severe falciparum malaria) ทำลาย RBC ทำให้เม็ดเลือดแดงแตก, cerebral malaria, blackwater fever, ARDS, AKI',
    vector: 'แพร่โดยยุงก้นปล่อง Anopheles เพศเมียเป็นพาหะ (vector)',
    additional: 'วินิจฉัย: Thin/Thick blood smear, RDT รักษา: Artemisinin-based combination therapy (ACT)'
  },
  {
    id: 'entamoeba',
    name: 'Entamoeba histolytica',
    thai: 'เชื้อบิดอะมีบา',
    kingdom: 'parasite',
    icon: '🪲',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Entamoeba_histolytica_01.jpg/640px-Entamoeba_histolytica_01.jpg',
    categories: ['type:protozoa'],
    characteristics: 'Protozoa มี 2 ระยะ: trophozoite (เคลื่อนที่ด้วย pseudopod, มี RBC ภายใน) และ cyst (4 nuclei) แยกจาก E. dispar ที่ไม่ก่อโรค',
    pathogenesis: 'บิดอะมีบา (amebic dysentery) ถ่ายเป็นมูกเลือด, amebic liver abscess (สีน้ำตาล anchovy paste)',
    vector: 'แพร่ทาง fecal-oral ผ่านน้ำและอาหารปนเปื้อน cyst',
    additional: 'วินิจฉัย: stool exam หา trophozoite/cyst, serology รักษา: Metronidazole + Paromomycin'
  },
  {
    id: 'giardia',
    name: 'Giardia lamblia',
    thai: 'เชื้อจิอาร์เดีย',
    kingdom: 'parasite',
    icon: '🪲',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Giardia_lamblia_SEM_8698_lores.jpg/640px-Giardia_lamblia_SEM_8698_lores.jpg',
    categories: ['type:protozoa'],
    characteristics: 'Flagellated protozoa รูปคล้ายว่าว มี 2 nuclei และ 4 คู่ flagella มี ventral disc สำหรับเกาะติดเยื่อบุลำไส้เล็ก',
    pathogenesis: 'Giardiasis — ท้องเสียเรื้อรัง อุจจาระมัน (steatorrhea) มีกลิ่นเหม็น ปวดท้อง ท้องอืด malabsorption โดยเฉพาะในเด็กและนักเดินทาง',
    vector: 'แพร่ทาง fecal-oral ผ่านน้ำดื่มที่ปนเปื้อน cyst (พบบ่อยในน้ำธรรมชาติ "beaver fever")',
    additional: 'วินิจฉัย: stool exam, antigen detection (ELISA) รักษา: Metronidazole, Tinidazole'
  },
  {
    id: 'toxoplasma',
    name: 'Toxoplasma gondii',
    thai: 'เชื้อทอกโซพลาสมา',
    kingdom: 'parasite',
    icon: '🪲',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Toxoplasma_gondii.jpg/640px-Toxoplasma_gondii.jpg',
    categories: ['type:protozoa'],
    characteristics: 'Apicomplexan, intracellular parasite มี 3 ระยะ: tachyzoite, bradyzoite (cyst), oocyst Definitive host คือ แมว',
    pathogenesis: 'Toxoplasmosis — ในคนปกติมักไม่มีอาการ คล้ายไข้หวัด ในผู้ภูมิคุ้มกันบกพร่อง (HIV/AIDS) เกิด encephalitis รุนแรง Congenital toxoplasmosis: ตาบอด, hydrocephalus, intracranial calcification',
    vector: 'กินเนื้อสัตว์ดิบที่มี cyst, สัมผัสอุจจาระแมวที่มี oocyst, จากแม่สู่ลูกผ่านรก',
    additional: 'วินิจฉัย: Serology IgM/IgG, PCR รักษา: Pyrimethamine + Sulfadiazine + Folinic acid'
  },
  {
    id: 'ascaris',
    name: 'Ascaris lumbricoides',
    thai: 'พยาธิไส้เดือน',
    kingdom: 'parasite',
    icon: '🪱',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Ascaris_lumbricoides.jpeg/640px-Ascaris_lumbricoides.jpeg',
    categories: ['type:helminth', 'helminth:nematode'],
    characteristics: 'พยาธิตัวกลม (Nematode) ขนาดใหญ่ที่สุดในลำไส้คน ตัวเมียยาว 20–35 cm ตัวผู้สั้นกว่า ไข่มี mammillated coat',
    pathogenesis: 'ปวดท้อง อุดตันลำไส้ (intestinal obstruction), Loeffler\'s syndrome (ตอนตัวอ่อนผ่านปอด), การขาดสารอาหารในเด็ก',
    vector: 'แพร่ทาง fecal-oral ผ่านดินและผักที่ปนเปื้อนไข่ embryonated egg',
    additional: 'วินิจฉัย: stool exam หาไข่ รักษา: Albendazole, Mebendazole'
  },
  {
    id: 'enterobius',
    name: 'Enterobius vermicularis',
    thai: 'พยาธิเข็มหมุด',
    kingdom: 'parasite',
    icon: '🪱',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Enterobius_vermicularis_LifeCycle.gif/640px-Enterobius_vermicularis_LifeCycle.gif',
    categories: ['type:helminth', 'helminth:nematode'],
    characteristics: 'พยาธิตัวกลมขนาดเล็ก ตัวเมียยาว 8–13 mm ปลายแหลมเหมือนเข็มหมุด ไข่รูปไข่ asymmetric (D-shape) ฟักเร็ว',
    pathogenesis: 'คันก้น (perianal pruritus) โดยเฉพาะกลางคืนเพราะตัวเมียวางไข่บริเวณ perianal area นอนไม่หลับ พบบ่อยในเด็ก',
    vector: 'แพร่ทาง fecal-oral, autoinfection (เกาแล้วดูดเข้าปาก), retroinfection',
    additional: 'วินิจฉัย: Scotch tape test (ปิดเทปที่ก้นตอนเช้า) รักษา: Albendazole, Mebendazole, Pyrantel pamoate รักษาทั้งครอบครัว'
  },
  {
    id: 'taenia',
    name: 'Taenia solium',
    thai: 'พยาธิตืดหมู',
    kingdom: 'parasite',
    icon: '🪱',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Taenia_saginata_adult_5260_lores.jpg/640px-Taenia_saginata_adult_5260_lores.jpg',
    categories: ['type:helminth', 'helminth:cestode'],
    characteristics: 'พยาธิตืด (Cestode) ตัวแบนเป็นปล้อง (proglottid) มี scolex 4 suckers + rostellum with hooks (armed) ยาวได้ 2–7 m',
    pathogenesis: 'Taeniasis (พยาธิตัวเต็มวัยในลำไส้) อาการน้อย, Cysticercosis เมื่อกินไข่เข้าไป ตัวอ่อนเข้าสมอง (neurocysticercosis) ทำให้ชัก',
    vector: 'กินเนื้อหมูดิบ/สุกๆ ดิบๆ ที่มี cysticercus, cysticercosis เกิดจากการกินไข่ปนเปื้อนอุจจาระ',
    additional: 'วินิจฉัย: stool exam, MRI/CT brain (cysticercosis) รักษา: Praziquantel, Albendazole + steroid'
  },
  {
    id: 'opisthorchis',
    name: 'Opisthorchis viverrini',
    thai: 'พยาธิใบไม้ตับ',
    kingdom: 'parasite',
    icon: '🪱',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Opisthorchis_viverrini_egg.png/640px-Opisthorchis_viverrini_egg.png',
    categories: ['type:helminth', 'helminth:trematode'],
    characteristics: 'พยาธิใบไม้ (Trematode) ตัวแบนรูปใบไม้ ขนาด 7–12 mm มี 2 sucker (oral + ventral) Hermaphrodite',
    pathogenesis: 'พยาธิใบไม้ตับ ก่อโรคในท่อน้ำดี cholangitis, cholangiocarcinoma (มะเร็งท่อน้ำดี) — ปัญหาสำคัญในภาคอีสาน',
    vector: 'กินปลาน้ำจืดเกล็ดขาวดิบ (ก้อยปลา ปลาส้ม) ที่มี metacercaria intermediate hosts: หอย และ ปลา',
    additional: 'วินิจฉัย: stool exam หาไข่ (operculated egg) รักษา: Praziquantel'
  },
  {
    id: 'schistosoma',
    name: 'Schistosoma mansoni',
    thai: 'พยาธิใบไม้เลือด',
    kingdom: 'parasite',
    icon: '🪱',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Schistosoma_20041.jpg/640px-Schistosoma_20041.jpg',
    categories: ['type:helminth', 'helminth:trematode'],
    characteristics: 'พยาธิใบไม้เลือด อาศัยใน mesenteric venules แยกเพศ (dioecious) ตัวผู้มีร่อง (gynaecophoric canal) อุ้มตัวเมีย ไข่มีหนามด้านข้าง',
    pathogenesis: 'Schistosomiasis (Bilharzia) — ไข่ที่ติดในเนื้อเยื่อก่อ granuloma ทำให้ตับโต ม้ามโต portal hypertension, hematuria (S. haematobium) เพิ่มความเสี่ยงมะเร็งกระเพาะปัสสาวะ',
    vector: 'Cercaria ในน้ำจืดไชเข้าผิวหนังโดยตรง intermediate host: หอยน้ำจืด',
    additional: 'วินิจฉัย: stool/urine exam, serology รักษา: Praziquantel'
  },
  {
    id: 'sarcoptes',
    name: 'Sarcoptes scabiei',
    thai: 'ไรหิด',
    kingdom: 'parasite',
    icon: '🕷️',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Sarcoptes_scabei_2.jpg/640px-Sarcoptes_scabei_2.jpg',
    categories: ['type:ectoparasite'],
    characteristics: 'ไร (mite) ขนาดเล็ก 0.3–0.4 mm 8 ขา ตัวเมียขุดรู (burrow) ในชั้นหนังกำพร้า วางไข่',
    pathogenesis: 'โรคหิด (Scabies) คันอย่างรุนแรง โดยเฉพาะกลางคืน ผื่นที่ง่ามนิ้ว ข้อมือ รักแร้ อวัยวะเพศ Norwegian/crusted scabies ในผู้ที่ภูมิคุ้มกันบกพร่อง',
    vector: 'แพร่ผ่านการสัมผัสผิวหนังโดยตรง ผ่านเครื่องนอน เสื้อผ้าที่ใช้ร่วมกัน',
    additional: 'รักษา: Permethrin 5% cream, Ivermectin oral ต้องรักษาคนใกล้ชิดและซักเครื่องนอนน้ำร้อน'
  },
  {
    id: 'pediculus',
    name: 'Pediculus humanus capitis',
    thai: 'เหาที่ศีรษะ',
    kingdom: 'parasite',
    icon: '🕷️',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Male_human_head_louse.jpg/640px-Male_human_head_louse.jpg',
    categories: ['type:ectoparasite'],
    characteristics: 'แมลง (insect) 6 ขา ขนาด 2–3 mm ไม่มีปีก ไข่ (nit) เกาะแน่นกับเส้นผมใกล้หนังศีรษะ',
    pathogenesis: 'Pediculosis capitis (เหา) คันศีรษะ เกิดผื่นจากการเกา อาจติดเชื้อแบคทีเรียซ้ำซ้อน พบบ่อยในเด็กวัยเรียน',
    vector: 'แพร่ผ่านการสัมผัสศีรษะโดยตรง การใช้หวี หมอน ผ้าเช็ดตัวร่วมกัน',
    additional: 'รักษา: Permethrin 1% shampoo, Malathion lotion, หวีสางไข่ (nit comb), ทำซ้ำที่ 7–10 วัน'
  },
];

// โครงสร้างหมวดหมู่ (สำหรับ sidebar)
const CATEGORY_TREE = [
  {
    id: 'bacteria',
    label: 'แบคทีเรีย (Bacteria)',
    kingdom: 'bacteria',
    groups: [
      {
        title: 'จำแนกตามรูปร่าง',
        items: [
          { id: 'shape:coccus', label: 'ค็อกคัส (Coccus)' },
          { id: 'shape:bacillus', label: 'บาซิลลัส (Bacillus)' },
          { id: 'shape:spirillum', label: 'สไปริลลัม (Spirillum)' },
          { id: 'shape:spirochete', label: 'สไปโรคีต (Spirochete)' },
        ],
      },
      {
        title: 'จำแนกตามการย้อมสีแกรม',
        items: [
          { id: 'gram:positive', label: 'แกรมบวก (Gram +)' },
          { id: 'gram:negative', label: 'แกรมลบ (Gram −)' },
        ],
      },
      {
        title: 'จำแนกตามออกซิเจน',
        items: [
          { id: 'oxygen:aerobic', label: 'Aerobic' },
          { id: 'oxygen:anaerobic', label: 'Anaerobic' },
          { id: 'oxygen:facultative', label: 'Facultative anaerobe' },
        ],
      },
    ],
  },
  {
    id: 'virus',
    label: 'ไวรัส (Virus)',
    kingdom: 'virus',
    groups: [
      {
        title: 'จำแนกตามสารพันธุกรรม',
        items: [
          { id: 'genetic:dna', label: 'DNA Virus' },
          { id: 'genetic:rna', label: 'RNA Virus' },
        ],
      },
      {
        title: 'จำแนกตามเยื่อหุ้ม',
        items: [
          { id: 'envelope:enveloped', label: 'Enveloped virus' },
          { id: 'envelope:naked', label: 'Non-enveloped (Naked)' },
        ],
      },
    ],
  },
  {
    id: 'parasite',
    label: 'ปรสิต (Parasites)',
    kingdom: 'parasite',
    groups: [
      {
        title: 'ประเภทปรสิต',
        items: [
          { id: 'type:protozoa', label: 'โปรโตซัว (Protozoa)' },
          { id: 'type:ectoparasite', label: 'ปรสิตภายนอก (Ectoparasites)' },
        ],
      },
      {
        title: 'หนอนพยาธิ (Helminths)',
        items: [
          { id: 'helminth:nematode', label: 'พยาธิตัวกลม (Nematodes)' },
          { id: 'helminth:cestode', label: 'พยาธิตัวแบน/ตืด (Cestodes)' },
          { id: 'helminth:trematode', label: 'พยาธิใบไม้ (Trematodes)' },
        ],
      },
    ],
  },
];
